import styles from "../styles/Home.module.scss";
import Head from "next/head";
import Header from "../components/Header";
import About from "../components/About";
import MainMenu from "../components/MainMenu";
import Contact from "../components/Contact";
import Footer from "../components/Footer";

export default function Home() {
  return (
    <div className={styles.main}>
      <Head>
        <title>Cloud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.top}>
        <Header></Header>
      </div>
      <About></About>
      <MainMenu></MainMenu>
      <Contact></Contact>
      <Footer></Footer>
    </div>
  );
}
