import styles from "../styles/Home.module.scss";
import Head from "next/head";
import NavBar from "../components/01-navigation/NavBar";
import Header from "../components/Header";
import About from "../components/About";
import MainMenu from "../components/MainMenu";
import DesktopProjectMenu from "../components/DesktopProjectMenu";
import Contact from "../components/Contact";

export default function Home() {
  return (
    <div className={styles.main}>
      <Head>
        <title>Cloud</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div className={styles.nav}>
        <NavBar></NavBar>
      </div>
      <div className={styles.top}>
        <Header></Header>
      </div>
      <About></About>
      <div className={styles.mobileMenu}>
        <MainMenu></MainMenu>
      </div>
      <div className={styles.desktopMenu}>
        <DesktopProjectMenu></DesktopProjectMenu>
      </div>
      <div></div>
      <Contact></Contact>
    </div>
  );
}
